x-default: &default
  image: vvakame/review:3.0
  volumes:
    - .:/workdir
  working_dir: /workdir

version: '3.4'
services:
  c94-copybook-compile:
    <<: *default
    entrypoint:
      - npm
      - run
      - pdf
  c94-copybook-lint:
    <<: *default
    entrypoint:
      - npm
      - run
      - lint
  c94-copybook-onlytex:
    <<: *default
    entrypoint:
      ["/bin/sh", "-c", "cd ./articles/book-pdf && uplatex -interaction=nonstopmode -file-line-error book.tex && uplatex -interaction=nonstopmode -file-line-error book.tex && uplatex -interaction=nonstopmode -file-line-error book.tex && dvipdfmx -d 5 -z 9 book.dvi"]
